### ISSUE TITLE
New "Esri Labs" text to be added in the app

### ISSUE THREAD

**Issue by sathyaprasad** [Esri/Trek2There#43]
Please add the following text at the end of "Disclaimer" text and "About" page as requested by @nitinsbajaj 

> Trek2There is an Esri Labs project and not an official Esri product. Trek2There is provided on an as-is-basis and you assume all risks associated with using this app. Please refer to the license agreement for further details.

**Comment by defiantgoat** [comment]
@nitinsbajaj @sathyaprasad Added text. Will be in next release.

**Comment by marikavertzonis** [comment]
I see the text in both places on android 4.2 (CT4) and iOS 8.4 (iphone 5), but because the first two paragraphs neatly fit on the screen i didn't know to scroll the text. Once i coincidentally scrolled it was apparent - but until then i thought the text was missing. Can you add an arrow that indicates that there is more text to view?

**Comment by marikavertzonis** [comment]
testing on more devices - android 7 (nexus 6), android 6.0.1 (samsung s6), ios 9.3 (iphone 6) and on these you can see the text gets cut of so you are 'encouraged' to touch and scroll. closing for now - scroll bars have presented problems of their own in other apps so the less UI here the better.
