### ISSUE TITLE
Video output is shown even if experimental features are not enabled

### ISSUE THREAD

**Issue by dominikargast** [Esri/Trek2There#70]
Make sure "use experimental features" in the settings page is not checked. Holding the phone upright, the video output stream is shown briefly, before being faded out again. The location marker and VR arrow on green ground are not displayed.

**Comment by dominikargast** [comment]
@marikavertzonis test with 3.0.5

**Comment by marikavertzonis** [comment]
on 3.0.5 on iphone 8 and trimble tdc (android 6) i see strange behaviour with the camera. to consistently repro:
 - go to settings page and enable experimental mode
 - go back to main page, see that when you tilt the device you get the camera view as expected when vertical
 - go back to settings page and disable experimental mode
 - go back to main page, see that camera mode is always enabled.

NB: on the iphone i didn’t need to enable experimental mode for this permanent camera behaviour - it happened when i did a fresh install and launch the app

**Comment by dominikargast** [comment]
@marikavertzonis test with 3.0.6

**Comment by marikavertzonis** [comment]
with 3.0.6 on
- iphone 8 (ios 11.2.5)
- trimble tdc100 (android 6)
- nexus 7 (android 7)
- windows 10 with classic x86 installer

very smooth transitions between horizontal (standard arrow view) and vertical (camera view) holding position of the device/app.

windows phone and windows desktop using UWP build - i get no camera view when in experimental mode. changing this issue to be specifically for UWP. the app doesn't crash, and i showed @shobanasuresh and she thinks its more likely to do with something in the tilt detection not being handled in UWP rather than the camera preview itself.

**Comment by marikavertzonis** [comment]
tested again in 3.0.17 and still same for UWP on windows phone and desktop - no camera view (but at lest no crash).
