### ISSUE TITLE
Remember last destination

### ISSUE THREAD

**Issue by dominikargast** [Esri/Trek2There#92]
As per request from @IsmaelInRedlands:

Remember the coordinates of the last destination used so that they are not lost when exiting the app.

**Comment by dominikargast** [comment]
@marikavertzonis @IsmaelInRedlands Last destination coordinates should now be saved. Please test with build 3.0.32

**Comment by marikavertzonis** [comment]
tested with 3.0.32 on Samsung S6 Android 6.0.1, Google Pixel 2 Android 8.1, Sony Xperia Android 7.1.1, iphone X and when you arrive, the destination is kept. this is consistent with the behavior observed whilst testing the arrival maths in #3. after you arrive, the coordinates are still preserved, because as you then walk away from it, the approaching messages are shown (with the expected increasing time and distances).
