### ISSUE TITLE
Error dialog issues

### ISSUE THREAD

**Issue by dominikargast** [Esri/Trek2There#96]
Corresponding AppFramework issue: https://devtopia.esri.com/Melbourne/appstudio-framework/issues/604

In addition, make sure that long error messages are wrapped correctly.

**Comment by dominikargast** [comment]
@marikavertzonis test with AppFramework 3.1.54 and Trek2There 3.0.36

**Comment by anshuman-mathur** [comment]
Tested Trek2There 3.0.36 Beta from HockeyApp which is built on AppFramework 3.1.58.

- Windows classic app: The following message is displayed when Trek2There cannot connect to a device. The error message is more meaningful and describes the reason why connection failed instead of displaying an error code.
![image](https://user-images.githubusercontent.com/22040375/41640083-c849f60e-74a3-11e8-89d8-9316b78ea027.png)


- Windows UWP app: The app does not finish connecting to the bluetooth GPS devices. The spinning image keeps on spinning indefinitely, indicating that the app is trying to connect to the GPS device.

**Comment by dominikargast** [comment]
Closing this issue since Mac, Android, iOS and Windows (classic) have been verified and the corresponding AppFramework issue has been closed.
